name: Decompile

on: [push]

jobs:
  decompile:
    name: Decompile

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
        
      - name: Unzip .so file
        run: |
          Expand-Archive libil2cpp.zip -DestinationPath .
        
      - name: Dump metadata
        shell: cmd
        run: |
          cd .tools/
          dump-metadata ../libil2cpp.so

      - name: Exporting the structure
        shell: cmd
        run: |
          cd .tools/
          il2cpp-inspector ^
            --bin ../libil2cpp.so ^
            --metadata global-metadata.dat ^
            --py-out unwanted/py.py ^
            --cpp-out unwanted/cpp ^
            --json-out unwanted/metadata.json ^
            --dll-out unwanted/dll ^
            --cs-out ../Dumped ^
            --layout tree ^
            --suppress-metadata ^
            --separate-attributes

      - name: Configure Git
        run: |
          git config --global core.autocrlf false  
          git config --global user.name "RaenonX"
          git config --global user.email "raenonx0710@gmail.com"

      - name: Commit exported resources (by repo dispatch)
        # git diff-index for checking if anything to commit
        run: |
          git add .
          git diff-index --quiet HEAD || git commit -m "Metadata of RaenonX-DL/dragalia-decompile@$Env:GITHUB_SHA"
